version: "3.9"

services:
  backend:
    build: ./backend/.
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: oop_project

  frontend:
    build: ./frontend/.
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
